SELECT TIPO_TARIFFA, ANNO, SUM(PREZZO) AS TOT_ANNO_TAR, SUM(SUM(PREZZO)) OVER () AS TOT, SUM(SUM(PREZZO)) OVER (PARTITION BY TIPO_TARIFFA) AS TOT_TAR, SUM(SUM(PREZZO)) OVER (PARTITION BY ANNO) AS TOT_ANNO
FROM FATTI F, TEMPO T, TARIFFA TA
WHERE f.id_tempo=t.id_tempo AND f.id_tar=ta.id_tar
GROUP BY TIPO_TARIFFA, ANNO