CREATE OR REPLACE TRIGGER SalesDepartment
AFTER UPDATE OF DNAME ON DIP
FOR EACH ROW
WHEN (OLD.DNAME='ACCOUNTING' AND NEW.DNAME='SALES')
begin
  update IMP
     set SAL=SAL + 100
   where DEPTNO=:NEW.DEPTNO;
end;